services:
  event-service:
    container_name: mzhn-event-service
    build:
      context: .
    env_file:
      - .env
    environment:
      WAIT_HOSTS: pg-es:5432
      PG_HOST: pg-es
      PG_PORT: 5432
      # ENV: local
    depends_on:
      - pg-es
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"

  pg-es:
    image: postgres:14.13-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - pg-es-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  pg-es-data:
    name: mzhn-es-pg
