// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/rabbitmq/amqp091-go"
	grpc2 "google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"log/slog"
	"mzhn/notification-service/internal/config"
	"mzhn/notification-service/internal/services/authservice"
	"mzhn/notification-service/internal/services/integrationservice"
	"mzhn/notification-service/internal/services/notificationservice"
	"mzhn/notification-service/internal/storage/amqp"
	"mzhn/notification-service/internal/storage/grpc/authapi"
	"mzhn/notification-service/internal/storage/grpc/eventsapi"
	"mzhn/notification-service/internal/storage/grpc/subscribersapi"
	"mzhn/notification-service/internal/storage/pg/integrationstorage"
	"mzhn/notification-service/internal/storage/pg/verificationstorage"
	amqp2 "mzhn/notification-service/internal/transport/amqp"
	"mzhn/notification-service/internal/transport/grpc"
	"mzhn/notification-service/internal/transport/http"
	"mzhn/notification-service/pb/authpb"
	"mzhn/notification-service/pb/espb"
	"mzhn/notification-service/pb/sspb"
	"mzhn/notification-service/pkg/sl"
	"time"
)

import (
	_ "github.com/jackc/pgx/stdlib"
)

// Injectors from wire.go:

func New() (*App, func(), error) {
	configConfig := config.New()
	authClient, err := _authpb(configConfig)
	if err != nil {
		return nil, nil, err
	}
	api := authapi.New(configConfig, authClient)
	service := authservice.New(configConfig, api)
	pool, cleanup, err := _pg(configConfig)
	if err != nil {
		return nil, nil, err
	}
	storage := integrationstorage.New(configConfig, pool)
	verificationstorageStorage := verificationstorage.New(configConfig, pool)
	integrationserviceService := integrationservice.New(configConfig, storage, storage, verificationstorageStorage, verificationstorageStorage)
	server := http.New(configConfig, service, integrationserviceService)
	channel, cleanup2, err := _amqp(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	subscriptionServiceClient, err := _sspb(configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	subscribersapiApi := subscribersapi.New(configConfig, subscriptionServiceClient)
	rabbitMQ := amqp.New(configConfig, channel)
	eventServiceClient, err := _espb(configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventsapiApi := eventsapi.New(configConfig, eventServiceClient)
	notificationserviceService := notificationservice.New(configConfig, subscribersapiApi, storage, rabbitMQ, api, eventsapiApi, eventsapiApi)
	rabbitMqConsumer := amqp2.New(configConfig, channel, notificationserviceService)
	grpcServer := grpc.New(configConfig, integrationserviceService)
	v := _servers(server, rabbitMqConsumer, grpcServer)
	app := newApp(configConfig, v)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func _pg(cfg *config.Config) (*pgxpool.Pool, func(), error) {
	ctx := context.Background()
	cs := cfg.Pg.ConnectionString()
	pool, err := pgxpool.New(ctx, cs)
	if err != nil {
		return nil, nil, err
	}
	slog.Debug("connecting to database", slog.String("cs", cs))
	t := time.Now()
	if err := pool.Ping(ctx); err != nil {
		slog.Error("failed to connect to database", slog.String("err", err.Error()), slog.String("conn", cs))
		return nil, func() { pool.Close() }, err
	}
	slog.Info("connected to database", slog.String("ping", fmt.Sprintf("%2.fs", time.Since(t).Seconds())))

	return pool, func() { pool.Close() }, nil
}

func _authpb(cfg *config.Config) (authpb.AuthClient, error) {
	addr := cfg.AuthService.ConnectionString()
	conn, err := grpc2.NewClient(addr, grpc2.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, err
	}

	return authpb.NewAuthClient(conn), nil
}

func _sspb(cfg *config.Config) (sspb.SubscriptionServiceClient, error) {
	addr := cfg.SubscriptionService.ConnectionString()
	conn, err := grpc2.NewClient(addr, grpc2.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, err
	}

	return sspb.NewSubscriptionServiceClient(conn), nil
}

func _espb(cfg *config.Config) (espb.EventServiceClient, error) {
	addr := cfg.EventsService.ConnectionString()
	conn, err := grpc2.NewClient(addr, grpc2.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, err
	}

	return espb.NewEventServiceClient(conn), nil
}

func _servers(http2 *http.Server, amqp3 *amqp2.RabbitMqConsumer, grpc3 *grpc.Server,
) []Server {
	servers := make([]Server, 0, 2)
	servers = append(servers, amqp3)
	servers = append(servers, http2)
	servers = append(servers, grpc3)
	return servers
}

func _amqp(cfg *config.Config) (*amqp091.Channel, func(), error) {

	cs := cfg.Amqp.ConnectionString()

	conn, err := amqp091.Dial(cs)
	if err != nil {
		return nil, nil, err
	}

	channel, err := conn.Channel()
	if err != nil {
		return nil, func() {
			conn.Close()
		}, err
	}

	if err := amqp_setup_exchange(cfg, channel, cfg.Amqp.NotificationsExchange, cfg.Amqp.NewEventsQueue, cfg.Amqp.UpcomingEventsQueue, cfg.Amqp.SubscriptionsQueue); err != nil {
		slog.Error("failed to setup notifications exchange", sl.Err(err))
		return nil, func() {
			channel.Close()
			conn.Close()
		}, err
	}

	if err := amqp_setup_exchange(cfg, channel, cfg.Amqp.SubscriptionExchange, cfg.Amqp.TelegramQueue, cfg.Amqp.MailQueue); err != nil {
		slog.Error("failed to setup subscribtions exchange", sl.Err(err))
		return nil, func() {
			channel.Close()
			conn.Close()
		}, err
	}

	return channel, func() {
		channel.Close()
		conn.Close()
	}, nil
}

func amqp_setup_exchange(cfg *config.Config, channel *amqp091.Channel, exchange string, queues ...string) error {

	log := slog.With(slog.String("exchange", exchange))
	log.Info("declaring exchange")
	if err := channel.ExchangeDeclare(exchange, "direct", true, false, false, false, nil); err != nil {
		slog.Error("failed to declare notifications queue", sl.Err(err))
		return err
	}

	for _, queueName := range queues {
		log.Info("declaring queue", slog.String("queue", queueName))
		queue, err := channel.QueueDeclare(queueName, true, false, false, false, nil)
		if err != nil {
			log.Error("failed to declare queue", sl.Err(err), slog.String("queue", queueName))
			return err
		}

		log.Info("binding queue", slog.String("queue", queueName))
		if err := channel.QueueBind(queue.Name, queueName, exchange, false, nil); err != nil {
			log.Error("failed to bind queue", sl.Err(err), slog.String("queue", queueName))
			return err
		}
	}

	return nil
}
