services:
  auth-service:
    container_name: mzhn-auth-service
    restart: always
    build:
      context: ../auth
    environment:
      WAIT_HOSTS: pg-auth:5432, redis-auth:6379
      PG_HOST: pg-auth
      PG_PORT: 5432
      PG_NAME: ${AUTH_SERVICE_PG_NAME}
      PG_USER: ${AUTH_SERVICE_PG_USER}
      PG_PASS: ${AUTH_SERVICE_PG_PASS}
      REDIS_HOST: redis-auth
      REDIS_PORT: 6379
      HTTP_PORT: 3000
      GRPC_PORT: 7000
      ENV: prod
    depends_on:
      - pg-auth
      - redis-auth
    ports:
      - "${AUTH_SERVICE_HTTP_PORT}:3000"
      - "${AUTH_SERVICE_GRPC_PORT}:7000"
    volumes:
      - ../auth/.env:/app/.env

  pg-auth:
    image: postgres:14.13-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_PG_NAME}
      POSTGRES_USER: ${AUTH_SERVICE_PG_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_PG_PASS}
    volumes:
      - pg-auth-data:/var/lib/postgresql/data

  redis-auth:
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - redis-auth-data:/data

volumes:
  pg-auth-data:
    name: mzhn-auth-pg
  redis-auth-data:
    name: mzhn-auth-redis
