include:
  - auth.yaml
  - event-service.yaml
  - rmq.yaml
  - subscriptions.yaml
  - parser.yaml
  - ai-search.yaml
  - notification-service.yaml
  - notifications-cron.yaml
  - telegram-bot.yaml

services:
  nginx:
    container_name: mzhn-nginx
    image: nginx:1-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - ai-search
      - notification-service
      - subscriptions-service
      - event-service
