services:
  notifications-cron-service:
    container_name: mzhn-notifications-cron
    restart: always
    build:
      context: ../notification-cron
    environment:
      APP_NAME: "notifications-crud"
      APP_VERSION: "1.0.0"

      SUBSCRIPTIONS_SERVICE_HOST: subscriptions-service
      SUBSCRIPTIONS_SERVICE_PORT: 7000

      EVENT_SERVICE_HOST: event-service
      EVENT_SERVICE_PORT: 7000

      AMQP_HOST: rmq
      AMQP_PORT: ${AMQP_PORT}
      AMQP_USER: ${AMQP_USER}
      AMQP_PASS: ${AMQP_PASS}

      AMQP_NOTIFICATIONS_EXCHANGE: ${AMQP_NOTIFICATIONS_EXCHANGE}
      AMQP_UPCOMING_EVENTS_QUEUE: ${AMQP_UPCOMING_EVENTS_QUEUE}

      ENV: prod
