services:
  subscriptions-service:
    container_name: mzhn-subscriptions-service
    restart: unless-stopped
    build:
      context: ../subscriptions/
    environment:
      WAIT_HOSTS: pg-ss:5432

      APP_NAME: "subscriptions"
      APP_VERSION: "1.0.0"

      PG_HOST: pg-ss
      PG_PORT: 5432
      PG_NAME: ${SUBSCRIPTIONS_SERVICE_PG_NAME}
      PG_USER: ${SUBSCRIPTIONS_SERVICE_PG_USER}
      PG_PASS: ${SUBSCRIPTIONS_SERVICE_PG_PASS}

      HTTP_ENABLED: true
      GRPC_ENABLED: true

      AUTH_SERVICE_HOST: auth-service
      AUTH_SERVICE_PORT: 7000

      EVENT_SERVICE_HOST: event-service
      EVENT_SERVICE_PORT: 7000

      HTTP_PORT: 80
      GRPC_PORT: 7000

      ENV: prod
    depends_on:
      - pg-ss
    ports:
      - "${SUBSCRIPTIONS_SERVICE_HTTP_PORT}:80"
      - "${SUBSCRIPTIONS_SERVICE_GRPC_PORT}:7000"

  pg-ss:
    container_name: mzhn-subscriptions-pg
    image: postgres:14.13-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SUBSCRIPTIONS_SERVICE_PG_NAME}
      POSTGRES_USER: ${SUBSCRIPTIONS_SERVICE_PG_USER}
      POSTGRES_PASSWORD: ${SUBSCRIPTIONS_SERVICE_PG_PASS}
    volumes:
      - pg-ss-data:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  pg-ss-data:
    name: mzhn-ss-pg
