// @generated by protobuf-ts 2.9.4 with parameter long_type_string
// @generated from protobuf file "notifications-service.proto" (package "notifications", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { NotificationService } from "./notifications-service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LinkTelegramResponse } from "./notifications-service";
import type { LinkTelegramRequest } from "./notifications-service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service notifications.NotificationService
 */
export interface INotificationServiceClient {
    /**
     * @generated from protobuf rpc: LinkTelegram(notifications.LinkTelegramRequest) returns (notifications.LinkTelegramResponse);
     */
    linkTelegram(input: LinkTelegramRequest, options?: RpcOptions): UnaryCall<LinkTelegramRequest, LinkTelegramResponse>;
}
/**
 * @generated from protobuf service notifications.NotificationService
 */
export class NotificationServiceClient implements INotificationServiceClient, ServiceInfo {
    typeName = NotificationService.typeName;
    methods = NotificationService.methods;
    options = NotificationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: LinkTelegram(notifications.LinkTelegramRequest) returns (notifications.LinkTelegramResponse);
     */
    linkTelegram(input: LinkTelegramRequest, options?: RpcOptions): UnaryCall<LinkTelegramRequest, LinkTelegramResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LinkTelegramRequest, LinkTelegramResponse>("unary", this._transport, method, opt, input);
    }
}
